name: trackhub
description: "Real time tracking application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # State management and DI
  get: ^4.7.3
  # Utility
  http: ^1.6.0
  toastification: ^3.0.3
  connectivity_plus: ^7.0.0
  smooth_page_indicator: ^2.0.1
  carousel_slider: ^5.1.2
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_messaging: ^16.1.1
  # Icons
  font_awesome_flutter: ^10.12.0
  iconsax_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/illustrations/
    - assets/images/logo/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400

        - asset: assets/fonts/Inter-Italic.otf
          weight: 400
          style: italic

        - asset: assets/fonts/Inter-Medium.otf
          weight: 500

        - asset: assets/fonts/Inter-MediumItalic.otf
          weight: 500
          style: italic

        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600

        - asset: assets/fonts/Inter-SemiBoldItalic.otf
          weight: 600
          style: italic

        - asset: assets/fonts/Inter-Bold.otf
          weight: 700

        - asset: assets/fonts/Inter-BoldItalic.otf
          weight: 700
          style: italic

        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800

        - asset: assets/fonts/Inter-ExtraBoldItalic.otf
          weight: 800
          style: italic

        - asset: assets/fonts/Inter-Black.otf
          weight: 900

        - asset: assets/fonts/Inter-BlackItalic.otf
          weight: 900
          style: italic